secrets:
  fly_token:
    file: ./flyio_token_gateway.txt

services:
  suspender:
    image: alpine:3.19
    command: ["sh", "/suspender.sh"]
    volumes:
      - ./suspender.sh:/suspender.sh:ro
      - ./notify.sh:/notify.sh:ro
      - ./activity:/activity
    secrets:
      - fly_token
    environment:
      - FLY_APP_NAME=wybory-jan-czechowski-com
      - MOST_RECENT_CALL_CHECK_FREQUENCY_S=10
      - MOST_RECENT_CALL_MAX_AGE_S=300
      - MACHINES_STATE_MAX_AGE_S=900
      - MACHINE_STARTED_MAX_NOTIFY_S=1800
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_EMAIL=${NTFY_EMAIL}
    restart: unless-stopped

  gateway:
    image: nginx:alpine
    entrypoint: ["sh", "/entrypoint.sh"]
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_RAW
      - NET_ADMIN
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./entrypoint.gateway.sh:/entrypoint.sh:ro
      - ./gateway.conf:/etc/wireguard/gateway.conf:ro
      - ./nginx-gateway.conf:/etc/nginx/templates/default.conf:ro
      - ./activity/:/activity
    environment:
      VIRTUAL_HOST: wybory.janczechowski.com
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: wybory.janczechowski.com
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
